application:
  debug: true
  logs:
    log_filename: "logs.txt"
    max_filesize: 5 # MB
    num_backups: 2

web_interface:
  host: "192.168.0.109"
  port: 8000

print_updates: false

connections: # Settings for connecting devices
  num_connection_tries: 5
  stall_time: 2 # seconds

#csv_data_logging:
#  base_filepath: "data"
#  lines_per_file: 50

websocket_streaming:
  host: "192.168.0.109"
  port: 8765

sql_database:
  sql_driver: "sqlite+aiosqlite"
  database_path: "db.sqlite"

devices:
  dyness_a48100:
    type: "DynessA48100Com"
    serial_port: "/dev/ttyUSB0"

  kodak_ogx_548:
    type: "KodakOGX548Inverter"
    serial_port: "/dev/ttyUSB1"
