application:
  debug: true
  logs:
    log_filename: "logs.txt"
    max_filesize: 5 # MB
    num_backups: 2

web_interface:
  host: "localhost"
  port: 8000
  protocol: "http"
  allowed_origins:
    - "*"

print_updates: false

connections: # Settings for connecting devices
  num_connection_tries: 5
  stall_time: 2 # seconds

websocket_streaming:
  host: "localhost"
  port: 8765

sql_database:
  sql_driver: "sqlite+aiosqlite"
  database_path: "/sunny_jim.db"

notifications:
  host: "http://192.168.0.102:9080"
  topic: "sunny_jim"
  grid_change_notifications: false
  low_battery_notifications: false
  low_battery_level_percentage: 25
  switch_action: "/devices/control/inverter/SWITCH_TO_LINE_MODE/"

devices:
  MockBattery:
    type: "MockBattery"
    voltage_value: 48.0
    current_value: 7.5
    soc_value: 0.4
    soh_value: 0.95
    cell_voltage_value: 3.5
    temperature_value: 18
    num_cells: 8

  MockInverter:
    type: "MockInverter"
