application:
  debug: true
  logs:
    log_filename: "logs.txt"
    max_filesize: 5 # MB
    num_backups: 2

web_interface:
  host: "192.168.0.109"
  port: 8000
  allowed_origins:
    - "*"

print_updates: false

connections: # Settings for connecting devices
  num_connection_tries: 5
  stall_time: 2 # seconds

#csv_data_logging:
#  base_filepath: "data"
#  lines_per_file: 50

websocket_streaming:
  host: "192.168.0.109"
  port: 8765

sql_database:
  sql_driver: "postgresql+asyncpg"
  database_path: "sunny_jim:sunny_jim@192.168.0.102:5432/sunny-jim"

notifications:
  host: "http://192.168.0.102:9080"
  topic: "sunny_jim"
  grid_change_notifications: false
  low_battery_notifications: false
  low_battery_level_percentage: 25
  switch_action: "/devices/control/inverter/SWITCH_TO_LINE_MODE/"
  icon_url: "https://github.com/stefvonb/sunny-jim/blob/main/web_interface/static/favicon.png?raw=true"

devices:
  dyness_a48100:
    type: "DynessA48100Com"
    serial_port: "/dev/ttyUSB0"

  kodak_ogx_548:
    type: "KodakOGX548Inverter"
    serial_port: "/dev/ttyUSB1"
