application:
  debug: true
  logs:
    log_filename: "logs.txt"
    max_filesize: 5 # MB
    num_backups: 2

web_interface:
  host: "localhost"
  port: 8000
  allowed_origins:
    - "*"

print_updates: false

connections: # Settings for connecting devices
  num_connection_tries: 5
  stall_time: 2 # seconds

websocket_streaming:
  host: "localhost"
  port: 8765

sql_database:
  sql_driver: "sqlite+aiosqlite"
  database_path: "/sunny_jim.db"

devices:
  MockBattery:
    type: "MockBattery"
    voltage_value: 48.0
    current_value: 7.5
    soc_value: 0.8
    soh_value: 0.95
    cell_voltage_value: 3.5
    temperature_value: 18
    num_cells: 8

  MockInverter:
    type: "MockInverter"
