application:
  debug: true
  logs:
    log_filename: "logs.txt"
    max_filesize: 5 # MB
    num_backups: 2

print_updates: false

connections: # Settings for connecting devices
  num_connection_tries: 5
  stall_time: 2 # seconds

csv_data_logging:
  base_filepath: "data"
  lines_per_file: 50

websocket_streaming:
  host: "0.0.0.0"
  port: 8765

devices:
  Dyness A48100:
    type: "DynessA48100Com"
    serial_port: "/dev/ttyUSB0"

  Kodak OGX 5.48:
    type: "KodakOGX548Inverter"
    serial_port: "/dev/ttyUSB1"
